-- Generated by @tenantscale/cli
-- Add tenant isolation to your tables
ALTER TABLE {{TABLE_NAME}} ADD COLUMN tenant_id UUID NOT NULL REFERENCES tenants(id);
CREATE INDEX idx_{{TABLE_NAME}}_tenant_id ON {{TABLE_NAME}}(tenant_id);
-- Enable RLS
ALTER TABLE {{TABLE_NAME}} ENABLE ROW LEVEL SECURITY;
